# Schema for the configuration files of the Plotly.Js module.

plotly_js.settings:
  type: config_object
  label: 'Plotly.Js settings'
  mapping:
    use_external:
      type: boolean
      label: 'Use External File'
    external_location:
      type: string
      label: 'External file location for plotly.js file'
    graph_template_path:
      type: string
      label: 'Location for user-modified graph template files'
    mapbox_access_token:
      type: string
      label: 'Access token for use with Mapbox mapping'
