name: Configuration Log
type: module
description: 'Logs changes to configuration.'
package: Configuration
# version: VERSION
core_version_requirement: ^8 || ^9
core: 8.x
configure: config_log.admin


# Information added by Drupal.org packaging script on 2020-07-08
version: '3.0.0'
project: 'config_log'
datestamp: 1594201077
